# section 1
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'apisix'

# section 2
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: apisix-metrics
    metrics_path : "/apisix/prometheus/metrics"
    static_configs:
     - targets: ["apisix:9091"]
